version: "3"
services:
  server:
    image: node:18
    volumes:
      - ./:/src
    ports:
      - "3000:3000"
    working_dir: /src
    command: npx docusaurus start --host 0.0.0.0
  web:
    image: httpd
    ports:
      - "8080:80"
  init:
    image: node:18
    profiles: ["deploy"]
    environment:
    - GIT_USER=helomach
    - GIT_PASS=
    - GIT_NAME="Heloisa Machado"
    - GIT_MAIL="heloisamachado84@gmail.com"
    - USE_SSH=false
    - CURRENT_BRANCH="main"
    volumes:
      - ./:/src
    working_dir: /src
    command: yarn deploy
